spring:
  application:
    name: springboard-example-web
  profiles:
    active: @profiles.active@
---
spring:
  config:
    activate:
      on-profile: development
dubbo:
  registry:
    address: zookeeper://localhost:2181
rocketmq:
  name-server: localhost:9876
  producer:
    group: springboard-example-web
  event-publisher:
    topic: springboard-example-eventbus
  event-subscriber:
    group: springboard-example-web
    topic: springboard-example-eventbus
server:
  port: 8000