spring:
  application:
    name: springboard-example-webapp
  profiles:
    active: @profiles.active@
---
spring:
  config:
    activate:
      on-profile: development
  redis:
    host: localhost
    port: 6379
dubbo:
  registry:
    address: zookeeper://localhost:2181
redis:
  event-publisher:
    group: springboard-example-webapp
    topic: springboard-example-eventbus
  event-subscriber:
    group: springboard-example-webapp
    topic: springboard-example-eventbus
#rocketmq:
#  name-server: localhost:9876
#  producer:
#    group: springboard-example-webapp
#  event-publisher:
#    topic: springboard-example-eventbus
#  event-subscriber:
#    group: springboard-example-webapp
#    topic: springboard-example-eventbus
server:
  port: 8000